name: Configure AWS

inputs:
  aws-profile:
    description: The AWS Profile name
    required: true
  role-to-assume: 
    description: The AWS Role for the account we want to access
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ inputs.role-to-assume }}
    - name: Set AWS Credentials file
      shell: bash
      run: |
        aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile ${{ inputs.aws-profile }}
        aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile ${{ inputs.aws-profile }}
        aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile ${{ inputs.aws-profile }}

