name: "Build"
on:
  workflow_call:
    inputs:
      image:
        description: "Name of the image we're building"
        required: true
        type: string
    outputs:
      digest:
        description: "Digest of the built image"
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        endpoint: builders
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build ${{ inputs.image }} container
      id: build
      uses: docker/build-push-action@v3
      with:
        context: ./${{ inputs.image }}
        platforms: linux/amd64
        file: ${{ inputs.image }}/.docker/Dockerfile.production
        push: ${{ github.event_name != 'pull_request' }}
        tags: teamleader/${{ inputs.image }}:latest, teamleader/${{ inputs.image }}:${{ github.sha }}
        cache-from: type=registry,ref=teamleader/${{ inputs.image }}:latest
        cache-to: type=inline
    - name: Set image build digest
      id: set-digest
      run: echo "digest=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
    outputs:
      digest: ${{ steps.set-digest.outputs.digest }}
