name: "Set matrix"
on:
  workflow_call:
    outputs:
      firstword:
        description: "Deploy matrix before e2e tests"
        value: ${{ jobs.set-matrix.outputs.matrix-no-e2e }}
      secondword:
        description: "Deploy matrix after e2e tests"
        value: ${{ jobs.set-matrix.outputs.matrix-e2e }}

jobs:
  set-matrix:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
      - name: Set Matrix
        id: set-matrix
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          echo "matrix-no-e2e=$(
              curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              https://api.github.com/repos/teamleadercrm/${{ github.event.repository.name }}/environments | jq -c '[ .environments[] | select(.protection_rules==[]).name ]'
          )" >> $GITHUB_OUTPUT
          echo "matrix-e2e=$(
              curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              https://api.github.com/repos/teamleadercrm/${{ github.event.repository.name }}/environments | jq -c '[ .environments[] | select(.protection_rules!=[]).name ]'
          )" >> $GITHUB_OUTPUT
    outputs:
        matrix-no-e2e: ${{ steps.set-matrix.outputs.matrix-no-e2e }}
        matrix-e2e: ${{ steps.set-matrix.outputs.matrix-e2e }}
